import Head from "next/head";
import Footer from "../footer/footer";
import Navbar from "../navbar/navbar";
import Subcription from "../subcription/subcription";

export default function login() {
  return (
    <>
      <div className="container">
        <Head>
          <title>Login Certiblock</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      {/*//navbar */}
      <Navbar />

      <div className="hero min-h-screen bg-base-200 bg-cover bg-center bg-no-repeat bg-fixed h-screen w-screen -mb-14"  style={{ backgroundImage: `url("https://cdn.discordapp.com/attachments/1032502035100225587/1041168926110928896/background.png")` }}>
        <div className="hero-content flex-col lg:flex-row-reverse">
          <div className="text-center lg:text-left">
            <h1 className="text-5xl font-bold text-success">Inicio de sesión</h1>
            <p className="py-6 font-bold text-success">
              Inicia sesión con tu cuenta de Certiblock para acceder a tu perfil
            </p>
          </div>
          <div className="card flex-shrink-0 w-full max-w-sm shadow-2xl bg-base-100">
            <div className="card-body">
              <div className="form-control">
                <input
                  type="text"
                  placeholder="Correo electrónico"
                  className="input input-bordered"
                />
              </div>
              <div className="form-control">
                <input
                  type="text"
                  placeholder="Contraseña"
                  className="input input-bordered"
                />
                <label className="label justify-end">
                  <a href="#" className="label-text-alt link link-hover text-success">
                    Olvidé mi contraseña
                  </a>
                </label>
              </div>
              <div className="form-control mt-4 mx-4 flex-row justify-center">
                <button className="btn btn-neutral rounded-full mx-4">Registrarse</button>
                <button className="btn btn-primary rounded-full mx-4">Iniciar sesión</button>
              </div>
            </div>
          </div>
        </div>
      </div>
      {/*//Subcription */}
      <Subcription />

      {/*//Footer */}
      <Footer/>
    </>
  );
}
