import Head from "next/head";

export default function botlle() {
  return (
    <>
      <div className="container">
        <Head>
          <title>Botlle Certiblock</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>

      <div className="flex justify-center h-max -mb-14">
        <div className="p-16 bg-neutral text-base-content md:rounded-t-[4.5rem] w-screen">
          <div className="flex flex-col items-center">
            <h1 className="text-4xl font-bold text-primary text-center">
              Certificado de origen en blockchain
            </h1>
            <h1 className="text-2xl font-bold p-4 text-success">
              Dueño:{" "}
              <span className="text-primary">
                Fábrica de Licores de Antioquia
              </span>
            </h1>

            <div className="flex justify-center p-4 scale-100 items-center">
              <img
                src="https://cdn.discordapp.com/attachments/1032502035100225587/1041112275878162483/logo-fla.png"
                alt="Logo"
                className="w-16 h-18"
              />
              <h1 className="text-white pt-4">
                <span className="text-primary">............</span>
                .............
              </h1>
              <img
                src="https://cdn.discordapp.com/attachments/1032502035100225587/1041112275538411650/logo-sin-cuadro.png"
                alt="Logo"
                className="w-16 h-18"
              />
              <h1 className="text-primary pt-4">
                <span className="text-white">............</span>
                .............
              </h1>
              <img
                src="https://cdn.discordapp.com/attachments/1032502035100225587/1041112276561821756/texto-certiblock.png"
                alt="Logo"
                className="mt-4 w-16 h-18"
              />
            </div>

            <h1 className="text-2xl text-error font-bold">IMPORTANTE</h1>
            <p className="text-center flex flex-col items center justify-left p-2 text-success">
              Te están vendiendo este producto como si estuviera sellado. Puedes
              denunciar con sólo tocar un botón.
            </p>
            <div className="justify-center">
              <button className="btn btn-error rounded-full text-3xl">
                DENUNCIAR
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="30"
                  height="30"
                  fill="currentColor"
                  className="bi bi-eye-fill ml-3"
                  viewBox="0 0 16 16"
                >
                  <path d="M9.05.435c-.58-.58-1.52-.58-2.1 0L.436 6.95c-.58.58-.58 1.519 0 2.098l6.516 6.516c.58.58 1.519.58 2.098 0l6.516-6.516c.58-.58.58-1.519 0-2.098L9.05.435zM8 4c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 4.995A.905.905 0 0 1 8 4zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                </svg>
              </button>
            </div>
            <p className="text-center flex flex-col items center justify-left p-2 text-success">
              Debido a que nuestro dominio puede ser copiado, asegúrate de que
              <span className="text-primary text-lg">este sí sea www.certiblock.co;</span>
              esto garantiza la legitimidad.
            </p>
          </div>
        </div>
      </div>
    </>
  );
}
