import Head from "next/head";
import Footer from "../footer/footer";
import Navbar from "../navbar/navbar";
import UserReclaim from "../reclaim/reclaim";

export default function Ureclaim() {
  return (
    <>
      <div className="container">
        <Head>
          <title>User Reclaim Certiblock</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      {/*//navbar */}
      <Navbar />

      <div className="min-h-screen bg-base-200 bg-cover bg-center bg-no-repeat bg-fixed h-screen w-screen">
        {/*//Subcription */}
        <UserReclaim />

        {/*//Footer */}
        <Footer />
      </div>
    </>
  );
}
