import Head from "next/head";
import Footer from "../footer/footer";
import Navbar from "../navbar/navbar";
import Bottle from "../bottle/bottle";
import Abottle from "../bottle/abottle";

export default function Ureclaim() {
  return (
    <>
      <div className="container">
        <Head>
          <title>User Reclaim Certiblock</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      {/*//navbar */}
      <Navbar />

      <div
        className="hero min-h-screen bg-base-200 bg-cover bg-center bg-no-repeat bg-fixed h-screen w-screen -mb-14 pb-20 flex justify-center"
        style={{
          backgroundImage: `url("https://cdn.discordapp.com/attachments/1032502035100225587/1041170715166134412/background3.jpg")`,
        }}
      >
        <div className="grid mt-4">
          <div className="hero-content justify-start">
              <img
                src="https://cdn.discordapp.com/attachments/1032502035100225587/1041142142325755945/ron-_abierta.png"
                className="max-w-sm rounded-lg shadow-2xl w-38 h-48"
              />
               <img
              src="https://cdn.discordapp.com/attachments/1032502035100225587/1041144145663774791/verificacion-rojo.png"
              alt="Logo"
              className="w-38 h-32"
            />
          </div>

          <div className="hero-content flex-col lg:flex-col mt-2 ">
            <h1 className="text-1xl font-bold text-success text-center">
              BOTELLA PREVIAMENTE ABIERTA
            </h1>

            <div className="flex justify-center space-x-4">
              <img
                src="https://cdn.discordapp.com/attachments/1032502035100225587/1041112275878162483/logo-fla.png"
                alt="Logo"
                className="w-12 h-10 mt-1"
              />
              <img
                src="https://cdn.discordapp.com/attachments/1032502035100225587/1041168299519639702/logo-light2.png"
                alt="Logo"
                className="w-17 h-7 mt-2"
              />
            </div>

            <div className="justify-center">
              <button className="btn btn-primary rounded-full">
                LOTE: A 12/12/22
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="16"
                  height="16"
                  fill="currentColor"
                  className="bi bi-eye-fill ml-3"
                  viewBox="0 0 16 16"
                >
                  <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z" />
                  <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z" />
                </svg>
                <span className="btn-text m-1 mt-1">1</span>
              </button>
            </div>
          </div>
          {/*//bottle atributes*/}
          <Abottle />
        </div>
      </div>

      {/*//Bottle */}
      <Bottle />

      {/*//Footer */}
      <Footer />
    </>
  );
}
