import Head from "next/head";

export default function reclaim() {
  return (
    <>
      <div className="container">
        <Head>
          <title>Reclaim Certiblock</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>

      <div className="flex justify-center h-max -mb-14">
        <div className="p-16 bg-neutral text-base-content md:rounded-t-[4.5rem] w-screen">
          <div className="flex flex-col items-center ">
            <h1 className="text-5xl font-bold text-primary">Importante</h1>
            <img src="https://cdn.discordapp.com/attachments/1032502035100225587/1041078055008997456/Certificacion_blanco.png" alt="Logo" className="p-6 w-24 h-30"/>
            <p className="text-center flex flex-col items center justify-left p-2 text-success">
                Ingresa el correo con el que solicitaste tu documento en la entidad, empresa o institución que te lo otorgó.
            </p>
            <p className="text-center flex flex-col items center justify-left p-2 text-success">
                A tu correo también llegará un mensaje para que puedas reclamar tu documento seguro.
            </p>
            <input
              type="text"
              placeholder="E-mail"
              className="input rounded-full input-primary w-full max-w-xs my-2"
            />
            <button className="btn-primary btn-xs rounded-full sm:btn-sm md:btn-md lg:btn-lg w-full max-w-xs my-2">
              RECLAMAR
            </button>
          </div>
        </div>
      </div>
    </>
  );
}
