import Head from "next/head";


export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Landing Certiblock</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="btn text-3xl font-bold underline bg-primary">Hello index!</h1>
    </div>
  );
}
