import Head from "next/head";

export default function navbar() {
  return (
    <>
      <div className="container">
        <Head>
          <title>Navbar Certiblock</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>

      <div className="navbar bg-base-300">
        <div className="flex-1 mt-2">
          <a className="btn btn-ghost normal-case text-xl">
            <img src="https://cdn.discordapp.com/attachments/1032502035100225587/1040928689111707658/logo-light.png" alt="Certiblock Logo" />
          </a>
        </div>

        <div className="flex-none mx-2">
          <button className="btn btn-square btn-ghost">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              className="inline-block w-5 h-5 stroke-current"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M4 6h16M4 12h16M4 18h16"
              ></path>
            </svg>
          </button>
        </div>
      </div>
    </>
  );
}
